@startuml
actor       User       as user
participant "Transfer User Svc" as svc
database    Postgres    as pg
queue       "SNS Topic" as SNS
user -> svc: request create transfer

svc -> pg: insert transfer data \nwith status: ACCEPTED

alt successful case

  svc -> SNS: publish message\nto deduct user balance
  svc -> user: response on create transfer

else failed case: duplicate transfer

  svc -> user: response on create transfer\nwith info: transfer duplicated
    
end

@enduml