@startuml
queue       "SQS Queue\nqueue:deduct balance" as SQS
participant "Deduct Balance Worker" as svc
database    Postgres    as pg
queue       "SNS Topic" as SNS

SQS -> svc: message received

svc -> pg: check balance

alt balance sufficient
  
  svc -> pg: deduct & update\nbalance

  svc -> pg: update transfer status into DEDUCTED

  svc -> SNS: publish message\nto proceed transfer

else balance insufficient

  svc -> pg: update transfer status into REJECTED

end

svc -> SQS: acknowledge message

@enduml