@startuml
participant Bank       as bank
participant "Transfer User Svc" as svc
database    Postgres    as pg
queue       "SNS Topic" as SNS

bank -> svc: request for callback transfer

svc -> svc: check transfer status

alt failed status

  svc -> pg: update transfer status into 'SUCCESS'

else 

  svc -> SNS: publish message\nto do reversal user balance

  svc -> pg: update transfer status into 'FAILED'
    
end

svc -> bank: response for callback transfer

@enduml