@startuml
(Start) ..> (Validate Bank Account)

(Validate Bank Account) ..> (Create Transfer)
note right of (Create Transfer) : transfer status : ACCEPTED

(Create Transfer) ..> (Deduct Balance)

(Deduct Balance) ..> (Reject Transfer)
note left of (Reject Transfer) : balance insufficient\ntransfer status : REJECTED

(Deduct Balance) ..> (Proceed Transfer)
note right of (Proceed Transfer) : Balance sufficient\ntransfer status : PROCCEED

(Proceed Transfer) ..> (Bank)

(Bank) ..> (Callback)
note right of (Callback) : if transaction 'succeeded'\n >> transfer status: SUCCEEDED\nif transaction 'failed'\n >> transfer status: FAILED" as NN

(Reject Transfer) ..> (End)

(Callback) ..> (End)

@enduml